#!/bin/bash

FS=/var/webdavfs

if [[ $LOGNAME != 'root' ]]; then
  echo 'This should run as root.'
  exit 1
fi

dd if=/dev/zero of=$FS bs=1024 count=30720
losetup dev/loop0 $FS
mkfs -t ext4 -v /dev/loop0
mkdir -p /mnt/webdav
echo Add following to /etc/fstab
echo /var/webdavfs	/mnt/webdav	ext4	defaults,noatime,loop	0	0
